"""Rebuild models/prod/registry.json from the model zips on disk.

The parallel retrain/sweep merge steps clobbered the prod registry. This
recreates a complete, consistent registry:

  - crypto pairs: entries recovered from models/prod_w0|w1 registries
    (the per-worker retrain registries, which the merge bug overwrote)
  - Yahoo 1d pairs: entries regenerated by backtesting each zip on the
    chronological last 20% of cached data with the production recipe
    (impact 0.25, dd floor 0.10), including bootstrap significance stats.
"""

import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bot.ai.backtest import metrics, rl_backtest
from bot.ai.bootstrap import bootstrap_ci, psr, sharpe_ci, sharpe_se
from bot.data.cache import DataCache
from config import settings

ROOT = Path(__file__).resolve().parent.parent
PROD = ROOT / "models" / "prod"
IMPACT = 0.25
DD_FLOOR = 0.10
YAHOO = ["^GSPC", "^IXIC", "^FTSE", "^GDAXI", "^N225", "EURUSD=X", "USDINR=X", "SLV"]


def periods_per_year(granularity: str) -> int:
    minutes = {"1m": 1, "5m": 5, "15m": 15, "1h": 60, "4h": 240, "1d": 1440}.get(granularity)
    if minutes is None:
        return 8760
    return int(525600 / minutes)


def add_bootstrap_stats(rec, curve, ppy):
    returns = curve.pct_change().dropna().to_numpy(dtype=np.float64)
    n = int(len(returns))
    sr = float(rec["sharpe"])
    if n < 30 or not np.isfinite(sr):
        rec["oos_sharpe_se"] = None
        rec["oos_psr"] = None
        rec["oos_sharpe_ci"] = None
        rec["oos_sharpe_ci_boot"] = None
        return rec
    rec["oos_sharpe_se"] = round(sharpe_se(sr, n, periods_per_year=ppy), 4)
    lo, hi = sharpe_ci(sr, n, periods_per_year=ppy)
    rec["oos_sharpe_ci"] = [round(lo, 3), round(hi, 3)]
    rec["oos_psr"] = round(psr(returns, benchmark_sharpe=0.0,
                               periods_per_year=ppy), 4)
    try:
        blo, bhi = bootstrap_ci(returns, n_boot=500, mean_block=20, seed=0)
        rec["oos_sharpe_ci_boot"] = [round(blo, 3), round(bhi, 3)]
    except Exception:
        rec["oos_sharpe_ci_boot"] = None
    return rec


def rebuild():
    cache = DataCache()
    registry = []

    # 1) crypto entries from the per-worker retrain registries
    for wdir in (PROD.parent / "prod_w0", PROD.parent / "prod_w1"):
        reg = wdir / "registry.json"
        if reg.exists():
            for entry in json.loads(reg.read_text()):
                if (entry["symbol"], entry["granularity"]) not in [
                    (e["symbol"], e["granularity"]) for e in registry
                ]:
                    registry.append(entry)
    print(f"recovered {len(registry)} crypto entries from prod_w*", flush=True)

    # 2) Yahoo 1d entries regenerated by backtest
    for sym in YAHOO:
        zipf = PROD / f"{sym}_1d.zip"
        if not zipf.exists():
            print(f"  SKIP {sym}: zip missing", flush=True)
            continue
        df = cache.load(sym, "1d")
        if df.empty or len(df) < 1000:
            print(f"  SKIP {sym}: no data ({len(df)} rows)", flush=True)
            continue
        from stable_baselines3 import PPO

        t0 = time.time()
        model = PPO.load(str(zipf), device="cpu")
        n_test = int(len(df) * 0.2)
        test_df = df.iloc[-n_test:]
        train_df = df.iloc[:-n_test]
        cross = {}
        for other in YAHOO:
            if other == sym:
                continue
            cdf = cache.load(other, "1d")
            if not cdf.empty:
                cross[other] = cdf
        from bot.data.features import feature_stats_for

        stats = feature_stats_for(train_df, cross_asset_dfs=cross)
        ppy = periods_per_year("1d")
        curve, trades = rl_backtest(
            test_df, model, window=60,
            spread=settings.SPREAD, slippage=settings.SLIPPAGE,
            entry_gate=0.0, feature_stats=stats, cross_asset_dfs=cross,
            impact_coef=IMPACT, max_dd_floor=DD_FLOOR,
        )
        m = metrics(curve, trades, periods_per_year=ppy)
        add_bootstrap_stats(m, curve, ppy)
        bh = float(test_df["close"].iloc[-1] / test_df["close"].iloc[60] - 1)
        entry = {
            "symbol": sym,
            "granularity": "1d",
            "model": f"{sym}_1d.zip",
            "created": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "data_rows": int(len(df)),
            "data_first": str(df.index[0]),
            "data_last": str(df.index[-1]),
            "cross_assets": list(cross),
            "timesteps": 300_000,
            "n_envs": 64,
            "window": 60,
            "net_arch": "1024,512",
            "entry_gate": 0.0,
            "trade_penalty": settings.TRADE_PENALTY,
            "risk_penalty": settings.RISK_PENALTY,
            "align_bonus": settings.ALIGN_BONUS,
            "entropy": 0.02,
            "seed": 42,
            "folds": [{
                "fold": 0,
                **m,
                "buy_hold": bh,
                "train_rows": int(len(train_df)),
                "test_rows": int(len(test_df)),
            }],
            "mean_oos_sharpe": float(m["sharpe"]),
            "market_impact_coef": IMPACT,
            "max_dd_floor": DD_FLOOR,
        }
        registry.append(entry)
        print(f"  {sym} 1d: S={m['sharpe']:.3f} PSR={m.get('oos_psr', 0):.2f} "
              f"trades={m['n_trades']} ({time.time()-t0:.0f}s)", flush=True)

    registry.sort(key=lambda e: (e["symbol"], e["granularity"]))
    (PROD / "registry.json").write_text(json.dumps(registry, indent=2))
    print(f"\nregistry rebuilt: {len(registry)} entries -> {PROD / 'registry.json'}")


if __name__ == "__main__":
    rebuild()